apiVersion: v1
kind: Service
metadata:
  name: {{ template "lena.fullname" . }}
  labels:
    app: {{ template "lena.name" . }}
    chart: {{ template "lena.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      {{ if and .Values.service.type (eq .Values.service.type "NodePort") }}
      nodePort: {{ .Values.service.nodePort }}
      {{ end }}
      protocol: TCP
      name: {{ .Values.service.name }}
    - port: 16900
      targetPort: 16900
      protocol: TCP
      name: {{ .Values.service.name }}-agent
  selector:
    app: {{ template "lena.name" . }}
    release: {{ .Release.Name }}
