apiVersion: v1
kind: Service
metadata:
  name: {{ template "lena.fullname" . }}
  labels:
    app: {{ template "lena.name" . }}
    chart: {{ template "lena.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ .Values.service.name }}
    - port: 16100
      targetPort: 16100
      protocol: UDP
      name: {{ .Values.service.name }}_udp
  selector:
    app: {{ template "lena.name" . }}
    release: {{ .Release.Name }}
